"storyline:ardent:title" = "Ардент"
"storyline:ardent:description" = "Пора поместить 'золото' и 'пиратство' в Золотой Век Пиратства! Похищения, кражи со взломом и откровенное пиратство - Чарльз Ардент делал все это! (Хотя есть те, кто утверждает, что Ардент - на самом деле была женщиной Хелен.)"

"storyline:assassin:title" = "Наёмник"
"storyline:assassin:description" = "Будучи бывшим голландским солдатом, Йоган Элтинг считается хорошим бойцом среди своих сверстников. Устав от армейской жизни (и армейского жалованья), он решил стать контрабандистом. Он ещё не знает, что скоро станет одним из самых страшных наемников на службе Испании. Но как долго он сможет продержаться?"

"storyline:bartolomeu:title" = "Бартоломью Португалец"
"storyline:bartolomeu:description" = "К 1660 году Португалия воевала с Испанией уже более 20 лет. Когда-то одна из главных морских сверхдержав, Португалия стала частью Испанской империи. В попытке переломить ситуацию португальское правительство раздало множество каперских патентов. Именно в такой обстановке Бартоломью решил покинуть свой дом и рискнуть в Новом Свете. Он и подумать не мог, что станет самым знаменитым португальским пиратом в истории, которого будут бояться испанцы и прославлять соотечественники."

"storyline:devlin_opera:title" = "Сага Девлинов"
"storyline:devlin_opera:description" = "Приключение, которое поможет Вам найти давно потерянных членов семьи и огромное сокровище... то есть, если Вы сможете выжить! По пути Вы встретите множество довольно ярких персонажей, которые помогут Вам в вашем путешествии. Вам предстоит сделать выбор, чья помощь Вам понадобится, а чья - нет. Ведь каждый персонаж предложит свой стиль в достижении Вашей цели."

"storyline:gold_bug:title" = "Золотой Жук"
"storyline:gold_bug:description" = """
'Эй, там! Эй, там! Этот парень танцует как сумасшедший! Его укусил Тарантул.'

Все пошло не так."""

"storyline:jack_sparrow:title" = "Поднять Флаг"
"storyline:jack_sparrow:description" = "О первых днях Джека Воробья было много предположений, и мы даже не уверены, что эта история полностью достоверна. Она объясняет некоторые события, сформировавшие этого печально известного пирата, но в зависимости от вашего выбора история может принять множество поворотов, которые могут закончиться или не закончиться тем, что вы уплывете в закат после снятия проклятия с Чёрной Жемчужины."
