"storyline:ardent:title" = "Ardent"
"storyline:ardent:description" = "¡Es hora de poner un poco de oro y de piratería en la Edad de Oro de la Piratería! Secuestro, robo y flagrantes actos piráticos... ¡Charles Ardent hace de todo! (Aunque no faltan quienes dicen que Ardent era en realidad una mujer, Helen)."

"storyline:assassin:title" = "Asesino"
"storyline:assassin:description" = "En su calidad de antiguo soldado holandés, Johan Elting es considerado por sus iguales como un buen luchador. Cansado de la vida (y la paga) militar, ha decidido convertirse en contrabandista. Poco puede imaginarse que pronto se convertirá en uno de los más famosos mercenarios al servicio de España. Pero, ¿por cuánto tiempo aceptará su nueva posición??"

"storyline:bartolomeu:title" = "Bartolomeu o Portugues"
"storyline:bartolomeu:description" = "En 1660, Portugal lleva más de veinte años en guerra con España. Antaño una de las grandes potencias marítimas, Portugal ha pasado décadas como parte del Imperio Español. En su lucha por la independencia, ha expedido muchas patentes de corso en un intento de cambiar el curso de la guerra. En este tumultuoso mundo, Bartolomeu decide abandonar su amado país y arriesgarse a viajar al Nuevo Mundo. No sabe que pronto se convertirá en el pirata portugués más famoso de la historia, temido por los españoles y vitoreado por sus compatriotas."

"storyline:devlin_opera:title" = "Ópera Devlin"
"storyline:devlin_opera:description" = "Una misión que te llevará a encontrar a tus parientes perdidos y un gran resoro... ¡si eres capaz de sobrevivir! Durante tu viaje a través de los vastos territorios del Nuevo Mundo, te encontrarás con varios personajes peculiares y aventuras que pondrán a prueba tus habilidades."

"storyline:gold_bug:title" = "El escarabjo de oro"
"storyline:gold_bug:description" = """
'¡Hola, hola! ¡Este hombre baila como un loco! Lo ha picado la tarántula'

Todo el revés."""

"storyline:jack_sparrow:title" = "Izad la Bandera"
"storyline:jack_sparrow:description" = "Se ha especulado mucho sobre los inicios de la carrera de Jack Sparrow y ni siquiera estamos seguros de si este testimonio en particular es completamente verídico. Explica algunos de los eventos que dieron forma a este infame pirata, pero el viaje puede dar múltiples giros y vueltas dependiendo de tus elecciones, lo que puede o no terminar contigo navegando hacia el atardecer después de levantar la maldición de la Perla Negra."
